version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  chatting-server:
    image: chatting
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    depends_on:
      - redis